### ISSUE TITLE
Terminologie

### ISSUE THREAD

**Issue by DonatienBaille** [Vince-LD/dwpy#2]
Hey Vincent,
Je viens de voir qu’il existait le Pipeline Design Pattern.
Il pourrait être intéressant d’utiliser la terminologie liée au pattern ?
Ex : source pour les données d’entrée et sink pour celles de sortie du pipeline ?

cf : https://www.startdataengineering.com/post/design-patterns/

Qu’en penses-tu ?

**Comment by Vince-LD** [comment]
Salut Donatien,

Merci pour la suggestion! Je suis carrément pour l'utilisation de noms/formats standards. Par contre je ne suis pas sûr d'à quel point ce sera applicable étant donné le design un peu ’spécial’ du la lib du au fait que je me sois engagé la dedans avec zéro connaissance.
C'est vrai que pour l'instant, un utilisateur est libre de faire des pipelines aussi tordus souhaite. Je pense que les source et sink ne seraient donc pas une mauvaise idée en tant que PipeNode spécifique.
